
package com.epam.web.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2019-06-15T14:27:18.500+03:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "UserFault", targetNamespace = "http://soap.web.epam.com/")
public class ServiceException extends Exception {
    
    private com.epam.web.soap.UserFault userFault;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.epam.web.soap.UserFault userFault) {
        super(message);
        this.userFault = userFault;
    }

    public ServiceException(String message, com.epam.web.soap.UserFault userFault, Throwable cause) {
        super(message, cause);
        this.userFault = userFault;
    }

    public com.epam.web.soap.UserFault getFaultInfo() {
        return this.userFault;
    }
}
