
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.epam.web.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2019-06-15T14:27:18.527+03:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "UserServiceImplService",
                      portName = "UserServiceImplPort",
                      targetNamespace = "http://soap.web.epam.com/",
                      wsdlLocation = "http://localhost:8080/IgorSasService/userSOAP?wsdl",
                      endpointInterface = "com.epam.web.soap.UserService")
                      
public class UserServiceImpl implements UserService {

    private static final Logger LOG = Logger.getLogger(UserServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.epam.web.soap.UserService#logIn(com.epam.web.soap.LoginModel  arg0 )*
     */
    public boolean logIn(com.epam.web.soap.LoginModel arg0) throws ServiceException    { 
        LOG.info("Executing operation logIn");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.epam.web.soap.UserService#getRoles(*
     */
    public java.util.List<com.epam.web.soap.Role> getRoles() throws ServiceException    { 
        LOG.info("Executing operation getRoles");
        try {
            java.util.List<com.epam.web.soap.Role> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.epam.web.soap.UserService#removeUser(com.epam.web.soap.User  arg0 )*
     */
    public boolean removeUser(com.epam.web.soap.User arg0) throws ServiceException    { 
        LOG.info("Executing operation removeUser");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.epam.web.soap.UserService#addUser(com.epam.web.soap.User  arg0 )*
     */
    public boolean addUser(com.epam.web.soap.User arg0) throws ServiceException    { 
        LOG.info("Executing operation addUser");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException("ServiceException...");
    }

    /* (non-Javadoc)
     * @see com.epam.web.soap.UserService#getAllUsers(*
     */
    public java.util.List<com.epam.web.soap.User> getAllUsers() { 
        LOG.info("Executing operation getAllUsers");
        try {
            java.util.List<com.epam.web.soap.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epam.web.soap.UserService#getUsersByRole(java.lang.String  arg0 )*
     */
    public java.util.List<com.epam.web.soap.User> getUsersByRole(java.lang.String arg0) throws ServiceException    { 
        LOG.info("Executing operation getUsersByRole");
        System.out.println(arg0);
        try {
            java.util.List<com.epam.web.soap.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceException("ServiceException...");
    }

}
